#--------------------------------分隔线  spring标准配置 --------------------------------
server:
  port: 8020
  session:
    timeout: 1800

security:
  basic:
    enabled: false

management:
  context-path: /actuator
  security:
    enabled: false

mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: classpath*:com.ssyt.**.domain

logging:
  level:
    com.zhiyang: debug
    
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true   
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.52:8066/merchant?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: ssytweb
    password: ssyt123456 
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: 192.168.10.5
      port: 6379
      timeout: 300
      password: 123456
      database: 1
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#  rabbitmq:
#    host: 192.168.10.5
#    port: 5672
#    username: dev
#    password: dev
#    connection-timeout: 30000
#    publisher-returns: true
#    cache:
#      channel:
#        size: 100
#    template:
#      receive-timeout: 3000
#    listener: 
#      acknowledge-mode: auto 
#      simple:
#        concurrency: 5
#        max-concurrency: 20
#        retry:
#          enabled: true


#-----------------------------分隔线  自定义配置  --------------------------------
custom:
  profile: pre
  cacheType: redis  #配置缓存和session存储方式，默认ehcache,可选redis    
  zhiyang:
    uploadPath: /home/images/merchant_admin/
  cipher:
    aeskey: 54B288D8F8F1E2C6CB203B92F25E8B3E
    keyAlgorithm: AES
    cipherAlgorithm: AES
    charset: UTF-8
  constants: 
    recommendUserId: 10 #后台创建店铺，临时写死的推荐人id,经营人id,代理id  
    userId: 10
    agentId: 5
  sso:
    profiles:
      active: pre
  uploadServer: 
    uploadFileUrl: http://192.168.10.9:8050/filesUploadForWangEditor #文件服务器地址
    viewFileUrl: http://192.168.10.9:8050/
  mail:
    #QQ邮件服务地址 
    host: smtp.qq.com
    #用户名
    username: 327713889@qq.com
    #密码（授权码）
    password: erocciwzjsgbbhgb
    #默认编码UTF-8
    default-encoding: UTF-8
    #端口，这里添加587即可
    port: 587
    fromMail:
      addr: 327713889@qq.com #邮件发送人
  api:
    ziguan:
      tokenUrl: http://192.168.10.46:9999/auth/oauth/token
      tokenUsername: admin
      tokenPassword: 123456
      currencyUrl: http://192.168.10.46:9999/zg/currency/all
      wealthUrl: http://192.168.10.46:9999/zg/account/wealth
      billUrl: http://192.168.10.46:9999/zg/bill/page
      billCommissionDetailUrl: http://192.168.10.46:9999/zg/commission/page
      billDetailUrl: http://192.168.10.46:9999/zg/bill/detail
      shopTotalProfitByShopsNoUrl: http://192.168.10.46:9999/zg/bill/shop/findProfitByShopNo
      shopTotalProfitByAccountNoUrl: http://192.168.10.46:9999/zg/bill/shop/findProfit
      findProfitUrl: http://192.168.10.46:9999/zg/bill/shop/findProfit
      cgjTradeDetailUrl: http://192.168.10.46:9999/zg/trade/currency/page
      cashOutToZiGuanUrl: http://192.168.10.46:9999/zg/trade/wallet/record
      updateCashOutToZiGuanUrl: http://192.168.10.46:9999/zg/trade/wallet/update
      pushPurseAccountToZiGuanUrl: http://192.168.10.46:9999/zg/account/sync/lianlian
    mall:
      pushShopsDataUrl: http://192.168.10.6/seller/action/registerStore
      pushShopsStatusUrl: http://192.168.10.6/seller/action/updateState
      pushOverdueTimeUrl: http://192.168.10.6/seller/action/renewStore
      addSelfStore: http://192.168.31.198:8001/seller/action/addSelfStore
      updateSelfStore: http://192.168.31.198:8001/seller/action/updateSelfStore