eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123456@172.18.130.78:8761/eureka/
security:
  basic:
    enabled: false
    
zhiyang:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    com.zhiyang: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.140.10:8066/merchant?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: ssytshopw3
    password: ssyt7Tetvwojagmv
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: 172.18.130.89
      port: 6379
      timeout: 300
      password: redis123
      database: 1
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#####邮箱信息#####
  mail:
    #QQ邮件服务地址 
    host: smtp.qq.com
    #用户名
    username: 327713889@qq.com
    #密码（授权码）
    password: erocciwzjsgbbhgb
    #默认编码UTF-8
    default-encoding: UTF-8
    #端口，这里添加587即可
    port: 587 
#邮件发送人
mail: 
  fromMail:
    addr: 327713889@qq.com

api:
  ziguan:
    tokenUrl: http://zg.33etong.com/auth/oauth/token
    tokenUsername: admin
    tokenPassword: 123456
    currencyUrl: http://zg.33etong.com/zg/currency/all
    wealthUrl: http://zg.33etong.com/zg/account/wealth
    billUrl: http://zg.33etong.com/zg/bill/page
    billCommissionDetailUrl: http://zg.33etong.com/zg/commission/page
    billDetailUrl: http://zg.33etong.com/zg/bill/detail
    shopTotalProfitByShopsNoUrl: http://zg.33etong.com/zg/bill/shop/findProfitByShopNo
    shopTotalProfitByAccountNoUrl: http://zg.33etong.com/zg/bill/shop/findProfit
    findProfitUrl: http://zg.33etong.com/zg/bill/shop/findProfit
    cgjTradeDetailUrl: http://zg.33etong.com/zg/trade/currency/page
    cashOutToZiGuanUrl: http://zg.33etong.com/zg/trade/wallet/record
    updateCashOutToZiGuanUrl: http://zg.33etong.com/zg/trade/wallet/update
  mall:
    pushShopsDataUrl: http://www.33etong.com/seller/action/registerStore
    pushShopsStatusUrl: http://www.33etong.com/seller/action/updateState
    pushOverdueTimeUrl: http://www.33etong.com/seller/action/renewStore
    addSelfStore: http://www.33etong.com/seller/action/addSelfStore
    updateSelfStore: http://www.33etong.com/seller/action/updateSelfStore

cipher:
  aeskey: 54B288D8F8F1E2C6CB203B92F25E8B3E
  keyAlgorithm: AES
  cipherAlgorithm: AES
  charset: UTF-8
  
#后台创建店铺，临时写死的推荐人id,经营人id,代理id  
constants:
  recommendUserId: 10
  userId: 10
  agentId: 5

#文件服务器地址
uploadServer: 
  uploadFileUrl: http://shimage.33etong.com/filesUploadForWangEditor
  viewFileUrl: http://shimage.33etong.com/ 